ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER ETHAN IDENTIFIED BY "Ethan9901"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE TO "ETHAN";
