ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ETHAN;

INSERT INTO TASKLIST (TASK_OWNER,TASK_NAME,TASK_TYPE,TASK_LEVEL,TASK_DESCRIPTION)
VALUES ('Ethan','Write README', 'Docs', 2, 'Document setup + run steps');

INSERT INTO TASKLIST (TASK_OWNER,TASK_NAME,TASK_TYPE,TASK_LEVEL,TASK_DESCRIPTION)
VALUES ('Ethan','Build adapter', 'Backend', 3, 'Create Oracle adapter for DAL');

INSERT INTO TASKLIST (TASK_OWNER,TASK_NAME,TASK_TYPE,TASK_LEVEL,TASK_DESCRIPTION)
VALUES ('Susan','Add validation', 'DB', 2, 'Constraints, unique keys, checks');

INSERT INTO USERS (USERNAME,PASSWORD,ROLE,EMAIL)
VALUES ('Ethan','$2a$12$aL84Fj.UCmKIa0wvVOJ4wggPGPetnQ32fkQ0t6V7KUaY5rdqd6pi.', 'ADMIN', 'ethanslade63@gmail.com');

COMMIT;

