ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ETHAN;

INSERT INTO TASKLIST (TASK_NAME, TASKTYPE, TASK_LEVEL, TASK_DESCRIPTION)
VALUES ('Write README', 'Docs', 2, 'Document setup + run steps');

INSERT INTO TASKLIST (TASK_NAME, TASKTYPE, TASK_LEVEL, TASK_DESCRIPTION)
VALUES ('Build adapter', 'Backend', 3, 'Create Oracle adapter for DAL');

INSERT INTO TASKLIST (TASK_NAME, TASKTYPE, TASK_LEVEL, TASK_DESCRIPTION)
VALUES ('Add validation', 'DB', 2, 'Constraints, unique keys, checks');

COMMIT;

